### ISSUE TITLE
Enhancement: Add SSM2044 Filter Board Files

### ISSUE THREAD

**Issue by DatanoiseTV** [pichenettes/shruthi-1#12]
It seems like the SSM2044 Filter PCB and Schematic (http://mutable-instruments.net/shruthi1/build/ssm2044) was actually never published in the Git Repository.

Are you planing to add those?

Thanks
Datanoise

**Comment by pichenettes** [comment]
Hi,

This is intentional. I removed the files from the git repository after
having discontinued this filter board. I really don't want to encourage
more people building it, especially since it doesn't do anything that
couldn't be done with the SMR4 filter board and mods.

Best,
Olivier

**Comment by fralalonde** [comment]
Shouldnt you close this issue as "will not fix"?

**Comment by pichenettes** [comment]
will not fix.
